from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field, ValidationError

from coding_agent.workspace.artifacts import build_artifact_registry
from coding_agent.workspace.run_paths import is_test_like_path
from coding_agent.core.llm_client import OpenAICompatClient
from coding_agent.core.utils import extract_json_object, truncate
from coding_agent.memory.reflexion_store import append_reflexion, build_reflexion_from_state
from coding_agent.repair.repair_controller import build_repair_controller, finalize_repair_controller
from coding_agent.scope.scope_contract import path_allows_modify
from .common import get_trace


class FailureOwnerDecision(BaseModel):
    failure_owner: str = Field(default="unknown")
    test_oracle_status: str = Field(default="not_checked")
    strategy: str = Field(default="fix_implementation")
    allowed_to_modify_tests: bool = False
    target_files: list[str] = Field(default_factory=list)
    reason: str = ""


FAILURE_OWNER_SYSTEM = """You are FailureOwnerClassifier for a general Coding Agent.
Return JSON only. Do not write prose.

Your job is to decide who owns the current failure and what repair strategy is allowed.
You must distinguish implementation bugs from generated-test oracle bugs.

Schema:
{
  "failure_owner": "implementation|generated_test|implementation_and_generated_test|external_test|tool_protocol|environment|requirement_ambiguity|unknown",
  "test_oracle_status": "not_checked|consistent|self_contradictory|inconsistent_with_contract|ambiguous_requirement",
  "strategy": "fix_implementation|fix_generated_test|inspect_more|clarify_assumption_in_report|stop_with_reason",
  "allowed_to_modify_tests": true,
  "target_files": ["relative/path.py"],
  "reason": "short operational reason"
}

Rules:
- User/external tests are constraints; do not mark them modifiable unless the task explicitly asks to edit tests.
- Tests generated by the agent may be corrected when the expected value is mathematically wrong, contradicts the comment, or contradicts the task contract.
- Correcting a wrong generated test is not weakening tests; deleting assertions or making tests vacuous is weakening tests.
- If the pytest failure shows an assertion where comment/calculation expects one value but assert uses another, classify generated_test when that test file is agent-generated.
- If uncertain, choose inspect_more.
"""


def _all_verification_text(state: dict[str, Any], limit: int = 12000) -> str:
    parts: list[str] = []
    for r in (state.get("verification") or {}).get("results", []) or []:
        parts.append(f"===== {r.get('name')} =====")
        parts.append("COMMAND: " + " ".join(r.get("command", [])))
        parts.append("RETURNCODE: " + str(r.get("returncode")))
        if r.get("stdout"):
            parts.append("STDOUT:\n" + r.get("stdout", ""))
        if r.get("stderr"):
            parts.append("STDERR:\n" + r.get("stderr", ""))
    return truncate("\n".join(parts), limit)


def _safe_read_many(workspace: str, paths: list[str], max_chars_each: int = 5000) -> dict[str, str]:
    root = Path(workspace).resolve()
    out: dict[str, str] = {}
    for rel in paths:
        try:
            p = (root / rel).resolve()
            if not str(p).startswith(str(root)) or not p.is_file():
                continue
            out[rel] = truncate(p.read_text(encoding="utf-8", errors="replace"), max_chars_each)
        except Exception as e:
            out[rel] = f"<read failed: {e}>"
    return out


def _candidate_files(state: dict[str, Any], registry: dict[str, Any]) -> list[str]:
    cand: list[str] = []
    failure = state.get("failure") or {}
    if failure.get("target_file"):
        rel = str(failure["target_file"]).replace("\\", "/")
        while rel.startswith("./"):
            rel = rel[2:]
        cand.append(rel)
    cand.extend((registry.get("test_files") or [])[:3])
    cand.extend((registry.get("code_files") or [])[:3])
    # Preserve order and unique.
    out: list[str] = []
    seen = set()
    for p in cand:
        if p and p not in seen:
            out.append(p)
            seen.add(p)
    return out[:6]


def _compact_registry(registry: dict[str, Any], candidates: list[str]) -> dict[str, Any]:
    candidate_set = set(candidates)
    artifacts = registry.get("artifacts") or {}
    if isinstance(artifacts, dict):
        selected_artifacts = {
            path: value
            for path, value in artifacts.items()
            if path in candidate_set
        }
    else:
        selected_artifacts = {}
    return {
        "agent_generated_tests": (registry.get("agent_generated_tests") or [])[:8],
        "external_tests": (registry.get("external_tests") or [])[:8],
        "test_files": (registry.get("test_files") or [])[:8],
        "code_files": (registry.get("code_files") or [])[:8],
        "candidate_artifacts": selected_artifacts,
    }


def _unambiguous_failure_owner_decision(
    state: dict[str, Any],
    controller: dict[str, Any],
    registry: dict[str, Any],
) -> FailureOwnerDecision | None:
    failure_type = str((state.get("failure") or {}).get("failure_type") or "")
    strong_implementation_failures = {
        "syntax_level_error",
        "import_level_error",
        "runtime_error",
        "name_error_impl",
        "attribute_error_impl",
    }
    deterministic_routes = {
        "rewrite_rejected_generated_file",
        "fix_test_registry",
        "complete_verification",
    }
    target = str((state.get("failure") or {}).get("target_file") or "").replace("\\", "/")
    direct_implementation_failures = {
        "syntax_level_error",
        "runtime_error",
        "name_error_impl",
        "attribute_error_impl",
    }
    if failure_type in direct_implementation_failures and target and not is_test_like_path(target):
        return FailureOwnerDecision(
            failure_owner="implementation",
            test_oracle_status="not_checked",
            strategy="fix_implementation",
            allowed_to_modify_tests=False,
            target_files=[target],
            reason="structured failure points directly to a non-test implementation file",
        )
    agent_tests = set(registry.get("agent_generated_tests") or [])
    allowed_source_paths = [
        str(path).replace("\\", "/")
        for path in (state.get("scope_contract") or {}).get("allowed_modify_paths") or []
        if path and not is_test_like_path(str(path))
    ]
    if (
        failure_type == "test_assertion_error"
        and target
        and is_test_like_path(target)
        and target not in agent_tests
        and not path_allows_modify(state.get("scope_contract"), target)
        and allowed_source_paths
    ):
        return FailureOwnerDecision(
            failure_owner="implementation",
            test_oracle_status="consistent",
            strategy="fix_implementation",
            allowed_to_modify_tests=False,
            target_files=allowed_source_paths,
            reason="an external protected test failed and the task names writable implementation files",
        )
    if failure_type not in strong_implementation_failures and str(controller.get("route") or "") not in deterministic_routes:
        return None
    owner = str(controller.get("failure_owner") or "unknown")
    strategy = str(controller.get("strategy") or "inspect_more")
    if owner == "unknown" or strategy == "inspect_more":
        return None
    return FailureOwnerDecision(
        failure_owner=owner,
        test_oracle_status="not_checked",
        strategy=strategy,
        allowed_to_modify_tests=owner in {"generated_test", "implementation_and_generated_test"},
        target_files=list(controller.get("target_files") or []),
        reason=str(controller.get("reason") or "deterministic repair evidence identifies the failure owner"),
    )


def _heuristic_decision(state: dict[str, Any], registry: dict[str, Any], files: dict[str, str]) -> FailureOwnerDecision:
    del registry, files
    failure = state.get("failure") or {}
    target = (failure.get("target_file") or "").replace("\\", "/")
    while target.startswith("./"):
        target = target[2:]
    if failure.get("failure_type") in {"syntax_level_error", "import_level_error", "runtime_error", "name_error_impl", "attribute_error_impl"}:
        return FailureOwnerDecision(
            failure_owner="implementation",
            test_oracle_status="not_checked",
            strategy="fix_implementation",
            allowed_to_modify_tests=False,
            target_files=[target] if target else [],
            reason="failure is a syntax/import/runtime implementation error",
        )
    return FailureOwnerDecision(
        failure_owner="unknown",
        test_oracle_status="ambiguous_requirement",
        strategy="inspect_more",
        allowed_to_modify_tests=False,
        target_files=[target] if target else [],
        reason="the LLM owner review failed and deterministic evidence is not conclusive",
    )


def _parse_decision(text: str) -> FailureOwnerDecision:
    obj = extract_json_object(text)
    return FailureOwnerDecision(**obj)


def failure_owner_node(state: dict) -> dict:
    trace = get_trace(state)
    registry = build_artifact_registry(state)
    state["artifact_registry"] = registry
    candidates = _candidate_files(state, registry)
    file_contents = _safe_read_many(state["workspace"], candidates, max_chars_each=3500)
    state["test_oracle_review"] = {
        "status": "pending",
        "candidate_files": candidates,
        "file_previews": {k: truncate(v, 1200) for k, v in file_contents.items()},
    }
    trace.event("failure_owner_start", failure=state.get("failure"), candidates=candidates, artifact_registry=registry)

    controller = build_repair_controller(state)
    state["repair_controller"] = controller
    decision = _unambiguous_failure_owner_decision(state, controller, registry)
    if decision is not None:
        state["failure_owner_mode"] = "deterministic"
        trace.event("failure_owner_deterministic", decision=decision.model_dump(), repair_controller=controller)
    else:
        compact_registry = _compact_registry(registry, candidates)
        prompt = (
            f"Task:\n{state.get('task')}\n\n"
            f"Task contract:\n{truncate(json.dumps(state.get('task_contract'), ensure_ascii=False), 5000)}\n\n"
            f"Active failure:\n{truncate(json.dumps(state.get('failure'), ensure_ascii=False), 4500)}\n\n"
            f"Verification output:\n{_all_verification_text(state, limit=7000)}\n\n"
            f"Artifact registry summary:\n{truncate(json.dumps(compact_registry, ensure_ascii=False), 4500)}\n\n"
            "Relevant file contents:\n"
            + truncate("\n\n".join(f"===== {p} =====\n{c}" for p, c in file_contents.items()), 10000)
            + "\n\nClassify the failure owner and strategy."
        )
        state["failure_owner_mode"] = "llm_oracle_review"
        state["failure_owner_prompt_chars"] = len(prompt)
        client = OpenAICompatClient("configs/model.yaml", messages_path=state["messages_path"])
        try:
            text = client.chat([
                {"role": "system", "content": FAILURE_OWNER_SYSTEM},
                {"role": "user", "content": prompt},
            ], purpose="failure_owner", max_tokens=900)
            decision = _parse_decision(text)
        except Exception as e:
            trace.event("failure_owner_llm_failed", error=str(e), fallback=True)
            decision = _heuristic_decision(state, registry, file_contents)

    # Preserve the model's grounded oracle review so the deterministic repair
    # router can distinguish a bad generated test from a failed implementation.
    state["test_oracle_review"] = {
        "status": decision.test_oracle_status,
        "failure_owner": decision.failure_owner,
        "strategy": decision.strategy,
        "allowed_to_modify_tests": decision.allowed_to_modify_tests,
        "target_files": list(decision.target_files),
        "reason": decision.reason,
        "candidate_files": candidates,
    }

    # Safety: never allow modifying external tests. Agent-generated tests may be
    # corrected only for generated_test or mixed implementation+generated_test failures.
    if decision.failure_owner not in {"generated_test", "implementation_and_generated_test"}:
        decision.allowed_to_modify_tests = False
    else:
        allowed = set(registry.get("agent_generated_tests") or [])
        filtered = []
        for p in decision.target_files:
            if p in allowed or (
                decision.failure_owner == "implementation_and_generated_test"
                and not (str(p).startswith("tests/") or Path(str(p)).name.startswith("test_"))
            ):
                filtered.append(p)
        decision.target_files = filtered or sorted(allowed)[:3]
        decision.allowed_to_modify_tests = bool(allowed)

    state["test_oracle_review"] = {
        "status": decision.test_oracle_status,
        "failure_owner": decision.failure_owner,
        "strategy": decision.strategy,
        "allowed_to_modify_tests": decision.allowed_to_modify_tests,
        "target_files": decision.target_files,
        "reason": decision.reason,
        "candidate_files": candidates,
    }
    controller = finalize_repair_controller(state, decision.model_dump(), base=controller)
    state["repair_controller"] = controller
    state["failure_owner"] = decision.failure_owner
    state["strategy_decision"] = decision.model_dump()
    state["strategy_decision"]["repair_controller_route"] = controller.get("route")
    state["test_oracle_review"].update({
        "status": decision.test_oracle_status,
        "failure_owner": decision.failure_owner,
        "strategy": decision.strategy,
        "allowed_to_modify_tests": decision.allowed_to_modify_tests,
        "target_files": decision.target_files,
        "reason": decision.reason,
    })
    try:
        refl = build_reflexion_from_state(state)
        path = append_reflexion(state["workspace"], refl)
        state.setdefault("reflexions", []).append(refl)
        state["reflexion_memory_path"] = str(path)
    except Exception as e:
        trace.event("reflexion_write_failed", error=str(e)[:1000])
    trace.event("failure_owner_done", strategy_decision=state["strategy_decision"], test_oracle_review=state["test_oracle_review"], reflexions=state.get("reflexions"))
    trace.snapshot(state)
    return state
